site_name: AGHub Documentation
site_description: Documentation for onboarding and working on AGHub
site_url: https://holstegelab.github.io/aghub_docs/
repo_url: https://github.com/holstegelab/aghub_docs
repo_name: holstegelab/aghub_docs
site_dir: site

docs_dir: docs

nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - Research Drive: research-drive.md
  - Installing Software: installing-software.md
